exclude_patterns:
- "benchmark/"
- "scripts/"
- "esm/"
- ".vscode/"
- "docs/"
- ".npmrc"
- ".nvmrc"
- ".gitignore"
- ".gitattributes"
- ".editorconfig"
- ".codeclimate.yml"
- "changelog-template.hbs"
- "CHANGELOG.md"
- "CODE_OF_CONDUCT.md"
- "CONTRIBUTING.md"
- "example.gif"
- "LICENSE.md"
- "package.json"
- "README.md"
- "yarn.lock"
- "src/**/?(*.)+(spec|test).[tj]s?(x)"
